### ISSUE TITLE
Give a useful error message when permission has not yet been granted for src/target/log path

### ISSUE THREAD

**Issue by dkadioglu** [ribbons/TaskerRsync#49]
Hi,

I stumbled upon your Tasker plugin and really love the idea. However, I cannot manage to get it running. After setting up the task, I always get a Permssion denied error, when rsync tries to access the local file. What I also never got is a permission dialog asking for file access, what I would have expected. If you need further info, please ask.

Thanks for this plugin idea and its implementation!

**Comment by dkadioglu** [comment]
Sorry, didn't find the right setting in Android settings. Now it works, closing this.

**Comment by ribbons** [comment]
I'm going to take the liberty of reopening this one because (as your experience attests), where to grant the permission really isn't obvious so a clearer error message would definitely be helpful to others.

**Comment by f92dev** [comment]
Hi, I have the same problem but I'm still not able to make it work (Permission denied).
In Android settings I don't see any manageable permissions.
Am I looking in the wrong place? I'm running Android 11, MIUI 12 (could be something related to Xiaomi phones, I don't know Android on the development side).

![IMG_20221207_231107](https://user-images.githubusercontent.com/17615321/206307738-13ecace3-4144-40f6-bd59-897395a502a2.jpg)

Thank you

**Comment by ribbons** [comment]
> Hi, I have the same problem but I'm still not able to make it work (Permission denied).
> In Android settings I don't see any manageable permissions.
> Am I looking in the wrong place? I'm running Android 11, MIUI 12 (could be something related to Xiaomi phones, I don't know Android on the development side).

It is (deliberately?) hard to find as it doesn't show under the settings for the app that you're (quite reasonably) looking under.  If you navigate to the top-level 'Apps' section in settings and scroll to the bottom there is an option called 'Special app access'.  If you tap through that and then pick 'All files access' at the top of the next screen you can then finally select 'Rsync for Tasker' and select the 'Allow access to manage all files' toggle.

May be some slight differences as I'm on Android 12 but from memory the setup for 11 is pretty similar - hope that helps!

**Comment by f92dev** [comment]
Found it under "Privacy protection" settings and then "Special permissions"!

Thank you for the tip and for this useful project

**Comment by ribbons** [comment]
> Found it under "Privacy protection" settings and then "Special permissions"!
> 
> Thank you for the tip and for this useful project

Great, no worries and glad you find it useful :+1:
